version: '3'

networks:
  trade-wise:

services:
  # Config Server
  config-server:
    build:
      context: .
      dockerfile: deployment/config-server.Dockerfile
    container_name: config-server
    environment:
      SPRING_PROFILES_ACTIVE: default
    ports:
      - "8888:8888"
    networks:
      - trade-wise
  # Eureka Server
  eureka-server:
    build:
      context: .
      dockerfile: deployment/eureka-server.Dockerfile
    container_name: eureka-server
    environment:
      SPRING_APPLICATION_NAME: eureka-server
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8888"
    ports:
      - "8761:8761"
    networks:
      - trade-wise
  # User Service
  user-service:
    build:
      context: .
      dockerfile: deployment/user.Dockerfile
    container_name: user-container
    environment:
      SPRING_APPLICATION_NAME: user-service
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8888"
    ports:
      - "8081:8081"
    networks:
      - trade-wise
  # Post Service
  post-service:
    build:
      context: .
      dockerfile: deployment/post.Dockerfile
    container_name: post-service
    environment:
      SPRING_APPLICATION_NAME: post-service
      SPRING_PROFILES_ACTIVE: native,dev
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8888"
    ports:
      - "8083:8083"
    networks:
      - trade-wise
  # Product Service
  product-service:
    build:
      context: .
      dockerfile: deployment/product.Dockerfile
    container_name: product-service
    environment:
      SPRING_APPLICATION_NAME: product-service
      SPRING_PROFILES_ACTIVE: native,dev
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8888"
    ports:
      - "8089:8089"
    networks:
      - trade-wise
  # Shop Service
  shop-service:
    build:
      context: .
      dockerfile: deployment/shop.Dockerfile
    container_name: shop-service
    environment:
      SPRING_APPLICATION_NAME: shop-service
      SPRING_PROFILES_ACTIVE: native,dev
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8888"
    ports:
      - "8088:8088"
    networks:
      - trade-wise
  # User info Service
  user-info-service:
    build:
      context: .
      dockerfile: deployment/user-info.Dockerfile
    container_name: user-info-service
    environment:
      SPRING_APPLICATION_NAME: user-info-service
      SPRING_PROFILES_ACTIVE: native,dev
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8888"
    ports:
      - "8084:8084"
    networks:
      - trade-wise
  # Category Service
  category-service:
    build:
      context: .
      dockerfile: deployment/category.Dockerfile
    container_name: category-service
    environment:
      SPRING_APPLICATION_NAME: category-service
      SPRING_PROFILES_ACTIVE: native,dev
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8888"
    ports:
      - "8087:8087"
    networks:
      - trade-wise
  # Chat Service
  chat-service:
    build:
      context: .
      dockerfile: deployment/chat.Dockerfile
    container_name: chat-service
    environment:
      SPRING_APPLICATION_NAME: chat-service
      SPRING_PROFILES_ACTIVE: native,dev
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8888"
    ports:
      - "8082:8082"
    networks:
      - trade-wise
  # Gateway
  gateway-service:
    build:
      context: .
      dockerfile: deployment/gateway.Dockerfile
    container_name: gateway-service
    environment:
      SPRING_APPLICATION_NAME: gateway-service
      SPRING_PROFILES_ACTIVE: native,dev
      SPRING_CONFIG_IMPORT: "configserver:http://config-server:8888"
    ports:
      - "8080:8080"
    networks:
      - trade-wise
volumes:
  keycloak-db-data: