version: '3'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=b2bDoc
      - POSTGRES_PASSWORD=b2b12!@
    ports:
      - '2345:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local