
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123
    url:  jdbc:postgresql://localhost:5432/jwt_db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8088

