spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:2023/postgres
    username: digitalAsset
    password: digitalAsset123@
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true