spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway-service
  profiles:
    active: dev, native
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8089
