spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  application:
    name: help-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8083